export const dataLauren = {
	generic: [
		{
			ask: ["laurenfraser"],
			text: ["Je ne sais pas quoi vous dire, nous ne sommes pas censés travailler sur le serial killer ?"],
			srcComment: "sounds/402-repliques-lauren-8.mp3",
		},
		{
			ask: ["celinevalluy"],
			text: ["Céline : 'Vous n'avez pas une enquête à résoudre plutôt que de vous inquiéter de ma vie ?'"],
			srcComment: "sounds/402-repliques-lauren-8.mp3",
		},
		{
			ask: ["timlonewood"],
			text: ["Tim : 'Vous ne devriez pas plutôt vous inquiéter de l'enquête ?'"],
			srcComment: "sounds/402-repliques-lauren-8.mp3",
		},
		{
			ask: ["raphaellesanchez"],
			text: [
				"Raphaëlle : 'Vous pourriez arrêter de jouer s'il vous plaît, on a une affaire de meurtre à résoudre tout de même !'",
			],
			srcComment: "sounds/402-repliques-lauren-8.mp3",
		},
		{
			ask: ["adeleleinu"],
			text: ["Adèle : 'Vous ne voulez pas vous concentrer sur l'enquête plutôt que d'ennuyer les membres de l'équipe ?'"],
			srcComment: "sounds/402-repliques-lauren-8.mp3",
		},
		{
			ask: ["rebeccadumont"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["mariannechauve"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["elodiebouchard"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["xaviermonrency"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["nicolaschaussee"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["konstantinwallner"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["jornfrenzel"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["anninakurschner"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["aaronking"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["rianodellavalle"],
			text: ["On ne peut pas joindre une victime décédée vous savez..."],
		},
		{
			ask: ["masonreynolds"],
			text: ["Ça ne répond pas..."],
		},
		{
			ask: ["fredericmasse"],
			text: ["Il semblerait que M. Masse ne soit plus en fonction, impossible de le joindre..."],
		},
		{
			ask: ["christophebrunelle"],
			text: ["Cet agent est désormais à la retraite. Il ne veut plus entendre parler de cette affaire."],
		},
		{
			ask: ["didierrodin"],
			text: ["J'ai bien trouvé l'agent mais je n'arrive pas à le joindre."],
		},
		{
			ask: ["christianpatenaude"],
			text: ["M. Patenaude est en vacances. Il ne souhaite être dérangé sous aucun prétexte m'a-t-on dit."],
		},
		{
			ask: ["charlesgarraud"],
			text: ["Charles Garraud est en prison, il va me falloir une bonne raison pour obtenir une entrevue."],
		},
		{
			ask: ["mariemarquis"],
			text: ["Je n'ai pas pu joindre cette agent, il semblerait qu'il soit décédé."],
		},
		{
			ask: ["jameschambers"],
			text: [
				"J'ai réussi à contacter M. Chambers avec succès, cependant, il indique qu'il ne dispose pas d'informations supplémentaires sur l'enquête pour le moment, en dehors de ce qui est déjà mentionné dans son rapport.",
			],
		},
		{
			ask: ["jeanpaulclot"],
			text: ["Je n'arrive pas à joindre ce monsieur, j'ai laissé un message..."],
		},
		{
			ask: ["loicvalluy"],
			text: ["Impossible de le trouver où que ce soit... Vous avez essayé les archives plutôt ?"],
		},
		{
			ask: ["agnesvouchiar"],
			text: ["Je n'arrive pas à les joindre... Ces médecins sont vraiment trop occupés."],
		},
		{
			ask: ["estellebarloigus"],
			text: ["Je n'ai rien trouvé sur cette personne, je vais continuer à chercher..."],
		},
		{
			ask: ["johannalesbourg"],
			text: ["Je n'ai pas réussi à joindre cette profileuse, elle doit être trop occupée"],
		},
		{
			ask: ["samuelperry"],
			text: ["Je crois qu'il nous a déjà tout dit."],
		},
		{
			ask: ["stellalouiseberg"],
			text: [
				"Je n'ai pas réussi à joindre cette personne, cela ne doit être qu'un pseudonyme d'auteur.",
				"Vous avez pensé à chercher sur Internet ?",
			],
		},
	],
	box1: [
		{
			ask: ["adeleleinu"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio2",
			title: "Interrogatoire Adèle Leinu",
			img1: "assets/photos-personnages/adele.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/106-interrogatoire-adele-lauren.mp3",
			srcTranscript: "assets/transcripts/106_Interrogatoire_Adele-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["alphonsesaintyves", "alphonsestyves"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio3",
			title: "Interrogatoire Alphonse St-Yves",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/107-interrogatoire-alphonse-st-yves-lauren.mp3",
			srcTranscript: "assets/transcripts/107_Interrogatoire_Alphonse_St_Yves-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["armandbeaux"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio4",
			title: "Interrogatoire Armand Beaux",
			img1: "assets/photos-personnages/Armand-Beaux.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/108-interrogatoire-armand-beaux-lauren.mp3",
			srcTranscript: "assets/transcripts/108_Interrogatoire_Armand_Beaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["axellecharpentier"],
			text: ["J'ai retrouvé un interrogatoire qui date de 1999, voici la retranscription :"],
			id: "box1audio5",
			title: "Interrogatoire Axelle Charpentier",
			img1: "assets/photos-personnages/Axelle-Charpentier.jpg",
			img2: "assets/photos-personnages/celine.jpg",
			srcAudio: "sounds/109-interrogatoire-axelle-charpentier-celine.mp3",
			srcTranscript: "assets/transcripts/109_Interrogatoire_Axelle_Charpentier-Celine_transcript.pdf",
			status: false,
		},
		{
			ask: ["camillemichaux"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio6",
			title: "Interrogatoire Camille Michaux",
			img1: "assets/photos-personnages/Camille-Michaux.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/110-interrogatoire-camille-michaux-lauren.mp3",
			srcTranscript: "assets/transcripts/110_Interrogatoire_Camille_Michaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["elisabethmonrency"],
			text: ["J'ai retrouvé un interrogatoire qui date de 1993, voici la retranscription :"],
			id: "box1audio7",
			title: "Interrogatoire Elisabeth Monrency",
			img1: "assets/photos-personnages/Elisabeth-Monrency.jpg",
			img2: "assets/photos-personnages/Christian-Patenaude.jpg",
			srcAudio: "sounds/111-interrogatoire-christian-patenaude-elisabeth-monrency.mp3",
			srcTranscript: "assets/transcripts/111_Interrogatoire_Christian_Patenaude-Elisabeth_Monrency_transcript.pdf",
			status: false,
		},
		{
			ask: ["emmanueldeslauriers"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio8",
			title: "Interrogatoire Emmanuel Deslauriers",
			img1: "assets/photos-personnages/Emmanuel-Deslauriers.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/112-interrogatoire-emmanuel-deslauriers-lauren.mp3",
			srcTranscript: "assets/transcripts/112_Interrogatoire_Emmanuel_Deslauriers-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["eugeniecourbis"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio9",
			title: "Interrogatoire Eugénie Courbis",
			img1: "assets/photos-personnages/Eugenie-Courbis.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/113-interrogatoire-eugenie-courbis-lauren.mp3",
			srcTranscript: "assets/transcripts/113_Interrogatoire_Eugenie_Courbis-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["maxencemaret"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio10",
			title: "Interrogatoire Maxence Maret",
			img1: "assets/photos-personnages/Maxence-Maret.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/114-interrogatoire-maxence-maret-lauren.mp3",
			srcTranscript: "assets/transcripts/114_Interrogatoire_Maxence_Maret-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["robertdumont"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio11",
			title: "Interrogatoire Robert Dumont",
			img1: "assets/photos-personnages/Robert Dumont.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/115-interrogatoire-robert-dumont-lauren.mp3",
			srcTranscript: "assets/transcripts/115_Interrogatoire_Robert_Dumont-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["patrickoneil", "patrickonil", "patrick"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio12",
			title: "Interrogatoire Patrick O'Neil",
			img1: "assets/photos-personnages/Patrick O'Neil.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/116-interrogatoire-patrick-o-neil-lauren.mp3",
			srcTranscript: "assets/transcripts/116_Interrogatoire_Patrick_O'Neil-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["violainecelier"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio13",
			title: "Interrogatoire Violaine Celier",
			img1: "assets/photos-personnages/Violaine-Cellier.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/117-interrogatoire-violaine-celier-lauren.mp3",
			srcTranscript: "assets/transcripts/117_Interrogatoire_Violaine_Celier-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["yannickbecot"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box1audio14",
			title: "Interrogatoire Yannick Bécot",
			img1: "assets/photos-personnages/Yannick-Becot.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/118-interrogatoire-yannick-becot-lauren.mp3",
			srcTranscript: "assets/transcripts/118_Interrogatoire_Yannick_Becot-Lauren_transcript.pdf",
			status: false,
		},
	],
	box2: [
		{
			ask: ["martinrichard"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box2audio1",
			title: "Interrogatoire Martin Richard",
			img1: "assets/photos-personnages/Martin Richard.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/205-interrogatoire-martin-richard-lauren.mp3",
			srcTranscript: "assets/transcripts/205_Interrogatoire_Martin_Richard-Lauren_transcript.pdf",
			status: false,
		},
		{
			ask: ["lindareynolds"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box2audio2",
			title: "Interrogatoire Linda Reynolds",
			img1: "assets/photos-personnages/Linda Reynolds.jpg",
			img2: "assets/photos-personnages/Jaden-Gill.jpg",
			srcAudio: "sounds/206-interrogatoire-linda-reynolds-agent-db.mp3",
			srcTranscript: "assets/transcripts/206_Interrogatoire_Linda_Reynolds-Jaden_Gill_transcript.pdf",
			status: false,
		},
		{
			ask: ["alphonsestyves", "alphonsesaintyves"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box2audio4",
			title: "Echange Alphonse St-Yves",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/208-interrogatoire-alphonse-saint-yves-lauren.mp3",
			srcTranscript: "assets/transcripts/208_Interrogatoire_Alphonse_Saint-Yves-Lauren_transcript.pdf",
			status: false,
		},
	],
	box3: [
		{
			ask: ["leoniebrugmann"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box3audio2",
			title: "Interrogatoire Leonie Brugmann",
			img1: "assets/photos-personnages/Leonie-Brugmann.jpg",
			img2: "assets/photos-personnages/Rebekka-Auer.jpg",
			srcAudio: "sounds/311-interrogatoire-leonie-brugmann-rebekka-auer.mp3",
			srcTranscript: "assets/transcripts/311_Interrogatoire_Leonie_Brugmann-Rebekka_Auer_transcript.pdf",
			status: false,
		},
		{
			ask: ["yannlacroix"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box3audio3",
			title: "Interrogatoire Yann Lacroix",
			img1: "assets/photos-personnages/Yann Lacroix.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/312-interrogatoire-yann-lacroix-raphaelle.mp3",
			srcTranscript: "assets/transcripts/312_Interrogatoire_Yann_Lacroix-Raphaelle_transcript.pdf",
			status: false,
		},
		{
			ask: ["francoisduchamp"],
			text: ["Je sors de l'interrogatoire, voici la retranscription :"],
			id: "box3audio4",
			title: "Interrogatoire François Duchamp",
			img1: "assets/photos-personnages/Francois-Duchamp.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/313-interrogatoire-francois-duchamp-raphaelle.mp3",
			srcTranscript: "assets/transcripts/313_Interrogatoire_Francois_Duchamp-Raphaelle_transcript.pdf",
			status: false,
		},
	],
};
