export const dataRaphaelle = {
	box1: [
		{
			ask: [
				"ruedestroisroismulhouse",
				"ruedesroismulhouse",
				"ruedestroisrois",
				"ruedesrois",
				"ruedes3roismulhouse",
				"ruedes3rois",
				"11ruedestroisroismulhouse",
				"11ruedesroismulhouse",
				"11ruedestroisrois",
				"11ruedesrois",
				"11ruedes3roismulhouse",
				"11ruedes3rois",
			],
			text: [
				"Ce lieu nous amène à Mulhouse, sur un chantier on dirait.",
				"Céline va me faire la courte échelle pour qu'on puisse passer le mur...",
			],
			id: "box1lieu1",
			src: "https://fouille.chantier.detectivebox.fr",
			status: false,
		},
		{
			ask: ["4346284115465"],
			text: [
				"On est en plein cœur du Puy-de-Dôme dans un coin paumé.",
				"Il n'y a qu'une seule maison qui a l'air abandonnée.",
				"Allons voir.",
			],
			id: "box1lieu2",
			src: "https://fouille.terrain.detectivebox.fr",
			status: false,
		},
		{
			ask: [
				"rtedardonardon",
				"parcdepartementaldesdolinesdelimere",
				"parcdepartementaldesdolinesdelimereardon",
				"parcdepartementallimere",
				"parcdepartementallimereardon",
				"parcdepartementaldesdolines",
				"parcdepartementaldesdolinesardon",
				"routedesaintcyrardon",
				"routesaintcyrardon",
				"rtedesaintcyrardon",
				"rtesaintcyrardon",
				"rtedardronardon",
				"routedardon",
				"parcdesdolinesdelimere",
				"parcdesdolinesdelimereardon",
				"parcdelimere",
				"parcdelimereardon",
				"parclimere",
				"parcdolineslimere",
				"parcdolineslimereardon",
				"leparcdesdolinesdelimere",
				"leparcdesdolinesdelimereardon",
			],
			text: [
				"Apparemment, c'est une maison à moitié en ruine avec le même triangle que sur le poème.",
				"J'y vais avec Lauren, espérons que ce ne soit pas un piège...",
			],
			id: "box1lieu3",
			src: "https://fouille.planque.detectivebox.fr",
			status: false,
		},
	],
	box2: [
		{
			ask: [
				"39southwaycolchesterco27ba",
				"39southwaycolchesterc027ba",
				"39southwaycolchester",
				"39southwaycolchesterco27baessex",
				"39southwaycolchesterc027baessex",
				"39southwaycolchesteressex",
			],
			text: ["J'ai fait envoyer un agent sur la dernière scène de crime.", "Voyons ce qu'il en ressort..."],
			id: "box2lieu1",
			src: "https://fouille.mason.detectivebox.fr",
			status: false,
		},
		{
			ask: [
				"20avcharlesdegaulle17450fouras",
				"20avenuecharlesdegaulle17450fouras",
				"20avcharlesdegaullefouras",
				"20avenuecharlesdegaullefouras",
			],
			text: ["Il semblerait que ce soit une petite maison, pas très bien entretenue.", "Allons voir ce que ça donne."],
			id: "box2lieu2",
			src: "https://fouille.appartement.detectivebox.fr",
			status: false,
		},
		{
			ask: [
				"prison",
				"prisongarraud",
				"prisondegarraud",
				"celluledegarraud",
				"celluledelaprisondegarraud",
				"cellulegarraud",
				"celluleprisongarraud",
				"prisoncharlesgarraud",
				"prisondecharlesgarraud",
				"celluledecharlesgarraud",
				"celluledelaprisondecharlesgarraud",
				"cellulecharlesgarraud",
				"celluleprisoncharlesgarraud",
			],
			text: ["La cellule de la prison de Garraud."],
			id: "box2lieu3",
			src: "https://fouille.prison.detectivebox.fr",
			status: false,
		},
	],
	box3: [
		{
			ask: [
				"8ruedeslilasbordeaux",
				"ruedeslilasbordeaux",
				"8ruedeslilasabordeaux",
				"ruedeslilasabordeaux",
				"8ruedeslilas33700bordeaux",
				"ruedeslilas33700bordeaux",
			],
			text: ["Domicile de Céline Valluy"],
			id: "box3lieu2",
			src: "https://fouille.celine.detectivebox.fr",
			status: false,
		},
		{
			ask: [
				"foretdesarbailles",
				"arbailles",
				"arbaille",
				"laforetdesarbailles",
				"lesarbailles",
				"foretarbaille",
				"foretdelarbaille",
				"laforetdelarbaille",
				"ite",
				"ithe",
				"dolmendite",
				"dolmendithe",
			],
			text: ["La forêt des Arbailles, d'où provient l'échantillon"],
			id: "box3lieu1",
			src: "https://fouille.foret.detectivebox.fr",
			status: false,
		},
	],
};
