export const dataTim = {
	box1: [
		{
			ask: [
				"vhs",
				"contenuvhs",
				"cassette",
				"vhscave",
				"cassettegarraud",
				"vieillevhs",
				"analysevhs",
				"analysecassette",
				"annalysecassettecharlesgarraud",
				"analysevhscharlesgarraud",
				"analysevhsgarraud",
			],
			text: [
				"Punaise ça faisait longtemps que je n'en avais pas vu !",
				"Alors, ne me demandez pas comment j'ai fait, mais j'ai découvert que la vidéo a été enregistrée le 17 janvier 1999.",
				"C'était cinq jours avant que Garraud ne se rende...",
				"Le passage intéressant est à 15 minutes, puis il y en a un autre à la fin, vers 20 minutes.",
			],
			srcComment: "sounds/101-commentaires-tim-1.mp3",
			id: "box1video3",
			title: "VHS",
			src: "videos/db-s02-103-def.mp4",
			status: false,
		},
		{
			ask: ["nozastrum", "nostrazrum"],
			text: [
				"Vous avez fait une recherche internet sur Nozastrum ?",
				"Moi ça m'a donné un profil LinkedIn.",
				"Voici le lien public :",
				"https://fr.linkedin.com/in/alphonse-saint-yves-nozastrum",
			],
			srcComment: "sounds/101-commentaires-tim-2.mp3",
			status: false,
		},
		{
			ask: [
				"ordinateurrebecca",
				"rebeccadumont",
				"ordinateurrebeccadumont",
				"ordinateurdumont",
				"portablerebecca",
				"portabledumont",
				"portablerebeccadumont",
				"ordinateurderebecca",
			],
			text: [
				"J'ai fouillé son historique et je pense que j'ai trouvé quelque chose qui va vous parler :",
				"un profil LinkedIn pour Nozastrum, dont son mari a parlé...",
				"Voici le lien public :",
				"https://fr.linkedin.com/in/alphonse-saint-yves-nozastrum",
			],
			srcComment: "sounds/101-commentaires-tim-3.mp3",
			status: false,
		},
		{
			ask: [
				"sitefandutueurautarot",
				"sitetueurautarot",
				"sitedufandutueurautarot",
				"siteletueurautarot",
				"sitefantueurtarot",
				"fantueurautarot",
				"websitefandutueurautarot",
				"websitetueurautarot",
				"websitedufandutueurautarot",
				"websiteletueurautarot",
				"websitefantueurtarot",
				"wwwfantueurtarotfr",
				"fantueurtarotfr",
			],
			text: [
				"Alors, voyons ce qu'on a là... Vous êtes allés le visiter ce site ?",
				"Vieux site web, le gars a dû le coder lui-même à l'époque, ça donne un truc préhistorique.",
				"Je vois pas d'espace pour se logger, ni d'identification possible.",
				"Rien de caché quoi…",
			],
			srcComment: "sounds/101-commentaires-tim-4.mp3",
			status: false,
		},
		{
			ask: ["fanduteurautarotgmailcom"],
			text: ["Une adresse e-mail ?", "Vous avez essayé de le contacter ?"],
			srcComment: "sounds/101-commentaires-tim-5.mp3",
			status: false,
		},
		{
			ask: [
				"wwwloteriedesastrescom",
				"loteriedesastrescom",
				"loterie",
				"loteriedesastres",
				"ticketloterie",
				"lotodesastres",
			],
			text: [
				"Alors, c'est marrant, le site a déjà été piraté.",
				"Ils ont renforcé la sécurité depuis, je peux y arriver, mais ça va me prendre trois plombes.",
				"Vous voulez pas faire le carré magique plutôt ?",
				"La somme de toutes les lignes, colonnes, diagonales, fait 34.",
				"Après, hop, vous mettez le numéro de ticket et on est bon.",
			],
			srcComment: "sounds/101-commentaires-tim-6.mp3",
			status: false,
		},
		{
			ask: [
				"lesommetdeshorizonscosmiques",
				"sommetdeshorizonscosmiques",
				"sommetdeshorizonscosmique",
				"lesommetdeshorizonscosmique",
				"conferencealphonse",
				"conferencealphonsestyves",
				"conferencealphonsesaintyves",
				"conferencenozastrum",
				"sommetastrologie",
			],
			text: [
				"J'ai réussi à récupérer la vidéo de la conférence, pas une mince affaire, c'était privé.",
				"Mais notre Nozastrum est bien dessus, son alibi est donc bien vérifié.",
			],
			srcComment: "sounds/101-commentaires-tim-7.mp3",
			status: false,
		},
	],
	box2: [
		{
			ask: ["webcam", "webcamappartement", "webcammason", "webcammasonreynolds", "webcamreynolds", "webcammason"],
			text: [
				"Vous m'avez demandé de m'occuper de la webcam de Reynolds.",
				"C'est intéressant, elle a une mémoire interne, protégée par un bon mot de passe, mais je l'ai craqué.",
				"Je vous envoie ce que j'ai trouvé dessus.",
				"Par contre je vous préviens, certains passages sont difficilement supportables.",
				"Je vous ai donc épargné de tout regarder en sélectionnant les moments les plus importants.",
			],
			srcComment: "sounds/201-commentaires-tim-1.mp3",
			id: "box2video2",
			title: "Webcam Mason Reynolds",
			src: "videos/db-s02-202-webcam-mason-v1.mp4",
			status: false,
		},
		{
			ask: [
				"fandesconstellationscachees",
				"fandesconstellationscachéesforum",
				"forumbreakingnews",
				"forum",
				"wwwfansdesconstellationscacheesfr",
				"wwwfandesconstellationscacheesfr",
				"fansdesconstellationscacheesfr",
				"fandesconstellationscacheesfr",
				"fansdesconstellationscachees",
				"fandesconstellationscachees",
				"fanconstellationscachees",
				"fansconstellationscachees",
				"fanconstellationscacheesfr",
				"fansconstellationscacheesfr",
				"sitefansdesconstellationscachees",
				"sitefandesconstellationscachees",
			],
			text: [
				"C'est une antiquité, que j'ai retrouvée au fin fond du web.",
				"https://www.fans-des-constellations-cachees.fr/",
				"J'ai tout déverrouillé pour les topics, mais j'arrive pas à casser les codes pour se connecter aux comptes et avoir accès aux messages privés.",
				"Par contre, en croisant les dates de connexion et les lieux, je pense avoir trouvé que le pseudo de Garraud était 'Rabid Star Slayer'.",
				"Pour les mots de passe, la seule obligation demandée, c'est d'être composés de chiffres et de lettres.",
				"Pas besoin de majuscules, ni de caractères spéciaux.",
			],
			srcComment: "sounds/201-commentaires-tim-2.mp3",
			status: false,
		},
		{
			ask: ["stellalouiseberg"],
			text: [
				"Alors le bouquin j'en sais rien, par contre, y a une youtubeuse qui a fait une vidéo là-dessus.",
				"Voici le lien :",
				"https://www.youtube.com/@LaurAstrologie",
			],
			srcComment: "sounds/201-commentaires-tim-3.mp3",
			status: false,
		},
		{
			ask: ["homosignorum"],
			text: ["Moi ça me dit rien, mais est-ce que vous avez pensé à regarder sur wikipedia ?"],
			srcComment: "sounds/201-commentaires-tim-4.mp3",
			status: false,
		},
	],
	box3: [
		{
			ask: [
				"boitemailannina",
				"emailannina",
				"boitemailanninakurschner",
				"emailanninakurschner",
				"dossieranninakurschner",
				"dossierannina",
				"anninakurschner",
				"irhemail",
				"wwwirhemailcom",
				"irhemailcom",
			],
			text: [
				"Ah je vois qu'il y a un email, je vais aller voir sur le webmail.",
				"Vous l'avez trouvé vous aussi ? C'est « www.irhemail.com »",
				"Voyons voir, ça a l'air bien vieux tout ça.",
				"Ha ha ! Voilà, j'ai son mot de passe.",
				"L'identifiant c'est son mail, celui du rapport.",
				"Le mot de passe c'est anni1971. Avec 2 « N ».",
				"Alors, c'est qui le meilleur ?",
			],
			srcComment: "sounds/302-commentaires-tim-1.mp3",
			status: false,
		},
		{
			ask: ["loicvalluy"],
			text: [
				"Loïc Valluy, voyons ce que je peux trouver sur lui...",
				"Bah pas grand-chose, j'ai juste trouvé que c'était un militaire.",
				"Ce type était peut-être déjà plus là quand Internet a commencé à être utilisé.",
				"Ah si, j'ai une photo, mais je vois pas ce que vous allez en faire.",
			],
			srcComment: "sounds/302-commentaires-tim-2.mp3",
			id: "box3document4",
			title: "Photo Loïc Valluy",
			src: "assets/document/314_Photo_Loic_Valluy.jpg",
			status: false,
		},
		{
			ask: ["wwwascleafr", "ascleafr", "asclea"],
			text: [
				"Il existe en effet un site là-dessus et qui correspond à notre affaire. Je vous laisse le regarder.",
				"Alors, si je cherche un peu plus, il y a un endroit où on peut accéder aux archives des patients décédés, sur la page histoire.",
				"C'est pas que je veux pas le pirater mais si je sais pas qui on cherche, ça va pas nous amener loin.",
				"Les numéros de patient sont composés de 6 chiffres en tout cas.",
			],
			srcComment: "sounds/302-commentaires-tim-3.mp3",
			status: false,
		},
		{
			ask: [
				"laurastrologie",
				"youtubelaurastrologie",
				"youtubeuselauratavernier",
				"youtubelauratavernier",
				"youtubeuselaurastrologie",
				"youtubeastrologie",
				"lauratavernier",
			],
			text: [
				"Alors, j'ai un peu enquêté sur sa vie, mais j'ai rien de transcendant.",
				"Elle est bien youtubeuse et elle a bien la maladie qu'elle dit.",
				"Elle s'est faite greffée en 2017, ça semble bien se passer pour elle.",
				"Je vois pas quoi vous dire de plus…",
			],
			srcComment: "sounds/302-commentaires-tim-4.mp3",
			status: false,
		},
		{
			ask: [
				"domicileceline",
				"appartementceline",
				"maisonceline",
				"adresseceline",
				"domicilecelinevalluy",
				"appartementcelinevalluy",
				"maisoncelinevalluy",
				"adressecelinevalluy",
			],
			text: [
				"J'ai pu avoir accès à ses informations fiscales et j'ai trouvé l'adresse de son domicile.",
				"Elle habite au 8 rue des Lilas à Bordeaux d'après ce que je lis ici.",
			],
			srcComment: "sounds/302-commentaires-tim-5.mp3",
			status: false,
		},
		{
			ask: ["treffenderlehrercom", "wwwtreffenderlehrercom", "treffenderlehrer", "treffenderlehren"],
			text: [
				"Il existe bien un site de rencontre là-dessus.",
				"Heureusement, on peut changer la langue.",
				"Par contre, j'arrive pas à le hacker celui-là",
			],
			status: false,
		},
	],
};
