export const dataHistory = {
	// ----- BOX 1 ----- //

	box1: [
		// ----- DOCUMENT ----- //

		{
			id: "box1document1",
			box: "Box 1",
			title: "Malle ouverte",
			category: "Document",
			detail: "Malle retrouvée sur le chantier où s'était rendue Rebecca Dumont",
			poster: "thumbnails/documents/101_Malle_ouverte_LD.jpg",
			src: "assets/document/101_Malle_ouverte_LD.jpg",
			status: false,
		},
		{
			id: "box1document2",
			box: "Box 1",
			title: "Carte lieu final",
			category: "Document",
			detail: "Une vue satellite d'un lieu et un étrange signe",
			poster: "thumbnails/documents/103_Carte_lieu_final_LD.jpg",
			src: "assets/document/103_Carte_lieu_final.jpg",
			status: false,
		},
		{
			id: "box1document3",
			box: "Box 1",
			title: "Guide du profiler",
			category: "Document",
			detail: "Guide écrit par Lauren Fraser et François Duchamp",
			poster: "thumbnails/documents/104_Guide_du_profiler_LD.jpg",
			src: "assets/document/104_Guide_du_profiler.pdf",
			status: false,
		},
		{
			id: "box1document4",
			box: "Box 1",
			title: "Rapport légiste Xavier Monrency",
			category: "Document",
			detail: "La victime 'oubliée' du Tueur au Tarot",
			poster: "thumbnails/documents/124_Rapport_legiste_Xavier_Monrency_LD.jpg",
			src: "assets/document/124_Rapport_legiste_Xavier_Monrency.jpg",
			status: false,
		},
		{
			id: "box1document5",
			box: "Box 1",
			title: "Email tueur",
			category: "Document",
			detail: "Email reçu du Tueur au Tarot après avoir retrouvé 'l'oublié'",
			poster: "thumbnails/documents/125_Email_Tueur_Oublie_LD.jpg",
			src: "assets/document/125_Email_Tueur_Oublie.jpg",
			status: false,
		},
		{
			id: "box1document6",
			box: "Box 1",
			title: "Message planque tueur",
			category: "Document",
			detail: "Message affiché au mur dans la planque du tueur",
			poster: "thumbnails/documents/126_Message_dans_la_planque_LD.jpg",
			src: "assets/document/126_Message_dans_la_planque.jpg",
			status: false,
		},
		{
			id: "box1document7",
			box: "Box 1",
			title: "Lettre pour Garraud",
			category: "Document",
			detail: "Lettre retrouvée dans une boîte en métal avec la VHS",
			poster: "thumbnails/documents/130_Lettre_pour_Garraud_LD.jpg",
			src: "assets/document/130_Lettre_pour_Garraud.jpg",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //
		{
			id: "box1audio1",
			box: "Box 1",
			title: "Derniers mots de Rebecca",
			category: "Audio",
			detail: "Attention, cet enregistrement est difficile à écouter",
			poster: "assets/photos-personnages/rebecca_dumont.jpg",
			img1: "assets/photos-personnages/rebecca_dumont.jpg",
			img2: null,
			srcAudio: "sounds/102-derniers-mots-rebecca.mp3",
			srcTranscript: "assets/transcripts/102_Derniers_mots_Rebecca_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio2",
			box: "Box 1",
			title: "Interrogatoire Adèle Leinu",
			category: "Audio",
			detail: "Médecin légiste sur l'affaire Rebecca Dumont",
			poster: "assets/photos-personnages/adele.jpg",
			img1: "assets/photos-personnages/adele.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/106-interrogatoire-adele-lauren.mp3",
			srcTranscript: "assets/transcripts/106_Interrogatoire_Adele-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio3",
			box: "Box 1",
			title: "Interrogatoire Alphonse St-Yves",
			category: "Audio",
			detail: "Voyant ayant eu une correspondance avec Rebecca Dumont",
			poster: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/107-interrogatoire-alphonse-st-yves-lauren.mp3",
			srcTranscript: "assets/transcripts/107_Interrogatoire_Alphonse_St_Yves-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio4",
			box: "Box 1",
			title: "Interrogatoire Armand Beaux",
			category: "Audio",
			detail: "Juge sur le procès de Charles Garraud",
			poster: "assets/photos-personnages/Armand-Beaux.jpg",
			img1: "assets/photos-personnages/Armand-Beaux.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/108-interrogatoire-armand-beaux-lauren.mp3",
			srcTranscript: "assets/transcripts/108_Interrogatoire_Armand_Beaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio5",
			box: "Box 1",
			title: "Interrogatoire Axelle Charpentier",
			category: "Audio",
			detail: "Interrogatoire datant de 1999 d'Axelle Charpentier : Astronome",
			poster: "assets/photos-personnages/Axelle-Charpentier.jpg",
			img1: "assets/photos-personnages/Axelle-Charpentier.jpg",
			img2: "assets/photos-personnages/celine.jpg",
			srcAudio: "sounds/109-interrogatoire-axelle-charpentier-celine.mp3",
			srcTranscript: "assets/transcripts/109_Interrogatoire_Axelle_Charpentier-Celine_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio6",
			box: "Box 1",
			title: "Interrogatoire Camille Michaux",
			category: "Audio",
			detail: "Elle a décrypté les lettres du tueur",
			poster: "assets/photos-personnages/Camille-Michaux.jpg",
			img1: "assets/photos-personnages/Camille-Michaux.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/110-interrogatoire-camille-michaux-lauren.mp3",
			srcTranscript: "assets/transcripts/110_Interrogatoire_Camille_Michaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio7",
			box: "Box 1",
			title: "Interrogatoire Elisabeth Monrency",
			category: "Audio",
			detail: "Interrogatoire datant de 1993 d'Elisabeth Monrency : épouse de Xavier Monrency",
			poster: "assets/photos-personnages/Elisabeth-Monrency.jpg",
			img1: "assets/photos-personnages/Elisabeth-Monrency.jpg",
			img2: "assets/photos-personnages/Christian-Patenaude.jpg",
			srcAudio: "sounds/111-interrogatoire-christian-patenaude-elisabeth-monrency.mp3",
			srcTranscript: "assets/transcripts/111_Interrogatoire_Christian_Patenaude-Elisabeth_Monrency_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio8",
			box: "Box 1",
			title: "Interrogatoire Emmanuel Deslauriers",
			category: "Audio",
			detail: "Inspecteur sur l'affaire Marianne Chauve",
			poster: "assets/photos-personnages/Emmanuel-Deslauriers.jpg",
			img1: "assets/photos-personnages/Emmanuel-Deslauriers.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/112-interrogatoire-emmanuel-deslauriers-lauren.mp3",
			srcTranscript: "assets/transcripts/112_Interrogatoire_Emmanuel_Deslauriers-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio9",
			box: "Box 1",
			title: "Interrogatoire Eugénie Courbis",
			category: "Audio",
			detail: "Inspectrice sur l'affaire Rebecca Dumont",
			poster: "assets/photos-personnages/Eugenie-Courbis.jpg",
			img1: "assets/photos-personnages/Eugenie-Courbis.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/113-interrogatoire-eugenie-courbis-lauren.mp3",
			srcTranscript: "assets/transcripts/113_Interrogatoire_Eugenie_Courbis-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio10",
			box: "Box 1",
			title: "Interrogatoire Maxence Maret",
			category: "Audio",
			detail: "Légiste sur le dossier Xavier Monrency",
			poster: "assets/photos-personnages/Maxence-Maret.jpg",
			img1: "assets/photos-personnages/Maxence-Maret.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/114-interrogatoire-maxence-maret-lauren.mp3",
			srcTranscript: "assets/transcripts/114_Interrogatoire_Maxence_Maret-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio11",
			box: "Box 1",
			title: "Interrogatoire Robert Dumont",
			category: "Audio",
			detail: "Epoux de Rebecca Dumont",
			poster: "assets/photos-personnages/Robert Dumont.jpg",
			img1: "assets/photos-personnages/Robert Dumont.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/115-interrogatoire-robert-dumont-lauren.mp3",
			srcTranscript: "assets/transcripts/115_Interrogatoire_Robert_Dumont-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio12",
			box: "Box 1",
			title: "Interrogatoire Patrick O'Neil",
			category: "Audio",
			detail: "Barman à l'Irish Bar de Mulhouse",
			poster: "assets/photos-personnages/Patrick O'Neil.jpg",
			img1: "assets/photos-personnages/Patrick O'Neil.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/116-interrogatoire-patrick-o-neil-lauren.mp3",
			srcTranscript: "assets/transcripts/116_Interrogatoire_Patrick_O'Neil-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio13",
			box: "Box 1",
			title: "Interrogatoire Violaine Celier",
			category: "Audio",
			detail: "Journaliste ayant suivi l'affaire du Tueur au Tarot",
			poster: "assets/photos-personnages/Violaine-Cellier.jpg",
			img1: "assets/photos-personnages/Violaine-Cellier.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/117-interrogatoire-violaine-celier-lauren.mp3",
			srcTranscript: "assets/transcripts/117_Interrogatoire_Violaine_Celier-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio14",
			box: "Box 1",
			title: "Interrogatoire Yannick Bécot",
			category: "Audio",
			detail: "Légiste sur le dossier de Nicolas Chaussée",
			poster: "assets/photos-personnages/Yannick-Becot.jpg",
			img1: "assets/photos-personnages/Yannick-Becot.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/118-interrogatoire-yannick-becot-lauren.mp3",
			srcTranscript: "assets/transcripts/118_Interrogatoire_Yannick_Becot-Lauren_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box1video1",
			box: "Box 1",
			title: "Briefing box 1",
			category: "Video",
			detail: "Une vieille affaire ressurgit ",
			poster: "thumbnails/video/db-s02-101-def-miniature.jpg",
			src: "videos/db-s02-101-def.mp4",
			status: false,
		},
		{
			id: "box1video2",
			box: "Box 1",
			title: "Fouille de la cave",
			category: "Video",
			detail: "Sanchez et Valluy fouillent la cave de la maison abandonnée",
			poster: "thumbnails/video/DB_S02_102_def_miniature.jpg",
			src: "videos/db-s02-102-def.mp4",
			status: false,
		},
		{
			id: "box1video3",
			box: "Box 1",
			title: "VHS",
			category: "Video",
			detail: "Une vieille VHS de Garraud",
			poster: "thumbnails/video/DB_S02_103_def_miniature.jpg",
			src: "videos/db-s02-103-def.mp4",
			status: false,
		},
		{
			id: "box1video4",
			box: "Box 1",
			title: "Interrogatoire de Charles Garraud",
			category: "Video",
			detail: "Sanchez et Fraser interrogent Garraud en prison",
			poster: "thumbnails/video/DB_S02_104_def_miniature.jpg",
			src: "videos/db-s02-104-vdef.mp4",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box1lieu1",
			box: "Box 1",
			title: "Chantier",
			category: "Lieu",
			detail: "Un chantier pour récupérer un gain de loterie ?! Curieux !",
			poster: "thumbnails/lieux/101_Chantier_low.jpg",
			src: "https://fouille.chantier.detectivebox.fr",
			status: false,
		},
		{
			id: "box1lieu2",
			box: "Box 1",
			title: "Terrain",
			category: "Lieu",
			detail: "A qui appartenait cette vieille maison abandonnée ?",
			poster: "thumbnails/lieux/102_Terrain_low.jpg",
			src: "https://fouille.terrain.detectivebox.fr",
			status: false,
		},
		{
			id: "box1lieu3",
			box: "Box 1",
			title: "Planque",
			category: "Lieu",
			detail: "Une planque sordide du Tueur au Tarot",
			poster: "thumbnails/lieux/103_Planque_1_low.jpg",
			src: "https://fouille.planque.detectivebox.fr",
			status: false,
		},

		// ----- ARCHIVES ----- //

		{
			id: "box1archive1",
			box: "Box 1",
			title: "Archives Alphonse StYves",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Alphonse_StYves.jpg",
			status: false,
		},
		{
			id: "box1archive2",
			box: "Box 1",
			title: "Archives Armand Beaux",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Armand_Beaux.jpg",
			status: false,
		},
		{
			id: "box1archive3",
			box: "Box 1",
			title: "Archives Axelle Charpentier",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Axelle_Charpentier.jpg",
			status: false,
		},
		{
			id: "box1archive4",
			box: "Box 1",
			title: "Archives Camille Michaux",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Camille_Michaux.jpg",
			status: false,
		},
		{
			id: "box1archive5",
			box: "Box 1",
			title: "Archives Charles Garraud",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Charles_Garraud.jpg",
			status: false,
		},
		{
			id: "box1archive6",
			box: "Box 1",
			title: "Archives Christian Patenaude",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Christian_Patenaude.jpg",
			status: false,
		},
		{
			id: "box1archive7",
			box: "Box 1",
			title: "Archives Christophe Brunelle",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Christophe_Brunelle.jpg",
			status: false,
		},
		{
			id: "box1archive8",
			box: "Box 1",
			title: "Archives Didier Rodin",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Didier_Rodin.jpg",
			status: false,
		},
		{
			id: "box1archive9",
			box: "Box 1",
			title: "Archives Elisabeth Monrency",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Elisabeth_Monrency.jpg",
			status: false,
		},
		{
			id: "box1archive10",
			box: "Box 1",
			title: "Archives Elodie Bouchard",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Elodie_Bouchard.jpg",
			status: false,
		},
		{
			id: "box1archive11",
			box: "Box 1",
			title: "Archives Emmanuel Deslauriers",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Emmanuel_Deslauriers.jpg",
			status: false,
		},
		{
			id: "box1archive12",
			box: "Box 1",
			title: "Archives Eugenie Courbis",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Eugenie_Courbis.jpg",
			status: false,
		},
		{
			id: "box1archive13",
			box: "Box 1",
			title: "Archives Frederic Masse",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Frederic_Masse.jpg",
			status: false,
		},
		{
			id: "box1archive14",
			box: "Box 1",
			title: "Archives Jacqueline Houdin",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Jacqueline_Houdin.jpg",
			status: false,
		},
		{
			id: "box1archive15",
			box: "Box 1",
			title: "Archives Johanna Lesbourg",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Johanna_Lesbourg.jpg",
			status: false,
		},
		{
			id: "box1archive16",
			box: "Box 1",
			title: "Archives Marianne Chauve",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Marianne_Chauve.jpg",
			status: false,
		},
		{
			id: "box1archive17",
			box: "Box 1",
			title: "Archives Marie Marquis",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Marie_Marquis.jpg",
			status: false,
		},
		{
			id: "box1archive18",
			box: "Box 1",
			title: "Archives Maxence Maret",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Maxence_Maret.jpg",
			status: false,
		},
		{
			id: "box1archive19",
			box: "Box 1",
			title: "Archives Nicolas Chaussee",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Nicolas_Chaussee.jpg",
			status: false,
		},
		{
			id: "box1archive20",
			box: "Box 1",
			title: "Archives Patrick O'Neil",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Patrick_Oneill.jpg",
			status: false,
		},
		{
			id: "box1archive21",
			box: "Box 1",
			title: "Archives Robert Dumont",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Robert_Dumont.jpg",
			status: false,
		},
		{
			id: "box1archive22",
			box: "Box 1",
			title: "Archives Violaine Celier",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/1_Archives_Violaine_Celier.jpg",
			status: false,
		},
		{
			id: "box1archive23",
			box: "Box 1",
			title: "Archives Xavier Monrency",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Xavier_Monrency.jpg",
			status: false,
		},
		{
			id: "box1archive24",
			box: "Box 1",
			title: "Archives Yannick Becot",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/1_Archives_Yannick_Becot.jpg",
			status: false,
		},
	],

	// ---- BOX 2 ---- //

	box2: [
		// ---- DOCUMENT ---- //

		{
			id: "box2document1",
			box: "Box 2",
			title: "Planque du tueur",
			category: "Document",
			detail: "Planque du tueur où des 'cadeaux' nous attendaient",
			poster: "thumbnails/documents/202_Planque_tueur_LD.jpg",
			src: "assets/document/202_Planque_tueur.png",
			status: false,
		},
		{
			id: "box2document2",
			box: "Box 2",
			title: "Livre ''Lilith et la guérison des maux''",
			category: "Document",
			detail: "Curieux livre écrit par une certaine Stella Louiseberg",
			poster: "thumbnails/documents/213_Livre_Lilith_incomplet_screenshot_LD.jpg",
			src: "assets/document/213_Livre_Lilith_incomplet.pdf",
			status: false,
		},
		{
			id: "box2document3",
			box: "Box 2",
			title: "Livre “Je commence l'Origami”",
			category: "Document",
			detail: "Livre 'Je commence l'origami' donné par Martin Richard dans la prison",
			poster: "thumbnails/documents/214_Livre_Origami_screenshot_LD.jpg",
			src: "assets/document/214_Livre_Origami.pdf",
			status: false,
		},
		{
			id: "box2document4",
			box: "Box 2",
			title: "Papier avalé par Garraud",
			category: "Document",
			detail: "Papier retrouvé dans le corps de Garraud après autopsie d'Adèle Leinu",
			poster: "thumbnails/documents/215_Papier_avale_LD.jpg",
			src: "assets/document/215_Papier_avale.jpg",
			status: false,
		},
		{
			id: "box2document5",
			box: "Box 2",
			title: "Lettre de Stella",
			category: "Document",
			detail: "Lettre de Stella Louiseberg retrouvée chez Mason Reynolds",
			poster: "thumbnails/documents/216_Lettre_de_Stella_LD.jpg",
			src: "assets/document/216_Lettre_de_Stella.jpg",
			status: false,
		},
		{
			id: "box2document6",
			box: "Box 2",
			title: "Notes sur Lauren Fraser",
			category: "Document",
			detail: "De curieuses notes du tueur sur Lauren Fraser et son mentor François Duchamp",
			poster: "thumbnails/documents/217_Message_sur_lieu_de_fouille_LD.png",
			src: "assets/document/217_Message_sur_lieu_de_fouille.png",
			status: false,
		},
		{
			id: "box2document7",
			box: "Box 2",
			title: "Poster Rabid Star Slayer",
			category: "Document",
			detail: "Poster d'un groupe de métal dans la celulle de Charles Garraud",
			poster: "thumbnails/documents/218_Poster_Rabid_Star_Slayer_LD.jpg",
			src: "assets/document/218_Poster_Rabid_Star_Slayer.png",
			status: false,
		},
		{
			id: "box2document8",
			box: "Box 2",
			title: "Email Lauren #1",
			category: "Document",
			detail: "Quelque chose ne tourne pas rond",
			poster: "thumbnails/documents/219_Message_Lauren_1_LD.jpg",
			src: "assets/document/219_Message_Lauren_1.jpg",
			status: false,
		},
		{
			id: "box2document9",
			box: "Box 2",
			title: "Email Lauren #2",
			category: "Document",
			detail: "Lauren enquête de son côté",
			poster: "thumbnails/documents/220_Message_Lauren_2_LD.jpg",
			src: "assets/document/220_Message_Lauren_2.jpg",
			status: false,
		},
		{
			id: "box2document10",
			box: "Box 2",
			title: "Photo Jacqueline Houdin",
			category: "Document",
			detail: "Photo de la mère de Charles Garraud retrouvée dans sa cellule",
			poster: "thumbnails/documents/221_Photo_Jacqueline_Houdin_LD.jpg",
			src: "assets/document/221_Photo_Jacqueline_Houdin.pdf",
			status: false,
		},
		{
			id: "box2document11",
			box: "Box 2",
			title: "Premier tri liste des victimes d'Eurocrim",
			category: "Document",
			detail: "Les 8 victimes qui correspondent à l'homme zodiacal",
			poster: "thumbnails/documents/211_Premier_tri_victimes_Eurocrim_LD.jpg",
			src: "assets/document/211_Premier_tri_victimes_Eurocrim.jpg",
			status: false,
		},
		{
			id: "box2document12",
			box: "Box 2",
			title: "5 victimes supplémentaires du Tueur",
			category: "Document",
			detail: "5 nouvelles victimes pour 5 cartes de Tarot...",
			poster: "thumbnails/documents/212_Victimes_Tueur_Tarot_Eurocrim_LD.jpg",
			src: "assets/document/212_Victimes_Tueur_Tarot_Eurocrim.jpg",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //

		{
			id: "box2audio1",
			box: "Box 2",
			title: "Interrogatoire Martin Richard",
			category: "Audio",
			detail: "Gardien de la prison de Charles Garraud",
			poster: "assets/photos-personnages/Martin Richard.jpg",
			img1: "assets/photos-personnages/Martin Richard.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/205-interrogatoire-martin-richard-lauren.mp3",
			srcTranscript: "assets/transcripts/205_Interrogatoire_Martin_Richard-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio2",
			box: "Box 2",
			title: "Interrogatoire Linda Reynolds",
			category: "Audio",
			detail: "Epouse de Mason Reynolds",
			poster: "assets/photos-personnages/Linda Reynolds.jpg",
			img1: "assets/photos-personnages/Linda Reynolds.jpg",
			img2: "assets/photos-personnages/Jaden-Gill.jpg",
			srcAudio: "sounds/206-interrogatoire-linda-reynolds-agent-db.mp3",
			srcTranscript: "assets/transcripts/206_Interrogatoire_Linda_Reynolds-Jaden_Gill_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio3",
			box: "Box 2",
			title: "Echanges Samuel Perry & Raphaëlle Sanchez",
			category: "Audio",
			detail: "Echanges entre Sanchez et Samuel Perry, agent de liaison d'Eurocrim",
			poster: "assets/photos-personnages/Samuel Perry.jpg",
			img1: "assets/photos-personnages/Samuel Perry.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/207-echanges-samuel-perry-raphaelle.mp3",
			srcTranscript: "assets/transcripts/207_Echanges_Samuel_Perry-Raphaelle_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio4",
			box: "Box 2",
			title: "Echange Alphonse St-Yves",
			category: "Audio",
			detail: "Voyant spécialiste en taromantie",
			poster: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "assets/photos-personnages/lauren.jpg",
			srcAudio: "sounds/208-interrogatoire-alphonse-saint-yves-lauren.mp3",
			srcTranscript: "assets/transcripts/208_Interrogatoire_Alphonse_Saint-Yves-Lauren_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box2video1",
			box: "Box 2",
			title: "Briefing box 2",
			category: "Video",
			detail: "C'est plus grave qu'on ne le pensait. Le tueur a de nouveau frappé",
			poster: "thumbnails/video/DB_S02_201_miniature.jpg",
			src: "videos/db-s02-201-vdef.mp4",
			status: false,
		},
		{
			id: "box2video2",
			box: "Box 2",
			title: "Webcam Mason Reynolds",
			category: "Video",
			detail: "La victime a réussi à filmer sa mort sans que le tueur ne s'en rende compte",
			poster: "thumbnails/video/db-s02-202-def-miniature.jpg",
			src: "videos/db-s02-202-webcam-mason-v1.mp4",
			status: false,
		},
		{
			id: "box2video3",
			box: "Box 2",
			title: "Flash Info",
			category: "Video",
			detail: "Charles Garraud vient d'être retrouvé pendu dans sa cellule ",
			poster: "thumbnails/video/DB_S02_203_def_miniature.jpg",
			src: "videos/db-s02-203-vdef.mp4",
			status: false,
		},
		{
			id: "box2video4",
			box: "Box 2",
			title: "Réfrigérateur",
			category: "Video",
			detail: "Sanchez a fait un sordide découverte dans la planque du tueur",
			poster: "thumbnails/video/DB_S02_207_def_miniature.jpg",
			src: "videos/db-s02-207-def.mp4",
			status: false,
		},
		{
			id: "box2video5",
			box: "Box 2",
			title: "Bureau de Lauren Fraser",
			category: "Video",
			detail: "Le tueur s'est introduit dans l'agence et a enlevé Lauren Fraser !",
			poster: "thumbnails/video/DB_S02_210_def_miniature.jpg",
			src: "videos/db-s02-209-vdef.mp4",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box2lieu1",
			box: "Box 2",
			title: "Chez Mason",
			category: "Lieu",
			detail: "Fouille de la scène de crime de Mason Reynolds",
			poster: "thumbnails/lieux/201_Chez_Mason_low.jpg",
			src: "https://fouille.mason.detectivebox.fr",
			status: false,
		},
		{
			id: "box2lieu3",
			box: "Box 2",
			title: "Cellule Garraud",
			category: "Lieu",
			detail: "Voilà donc où Garraud a passé les 20 dernières années de sa vie",
			poster: "thumbnails/lieux/202_Prison_cellule_Garraud_low.jpg",
			src: "https://fouille.prison.detectivebox.fr",
			status: false,
		},
		{
			id: "box2lieu2",
			box: "Box 2",
			title: " Appartement Stella",
			category: "Lieu",
			detail: "Une nouvelle planque de notre tueur, tout aussi accueillante ",
			poster: "thumbnails/lieux/203_Planque_2_appartement_low.jpg",
			src: "https://fouille.appartement.detectivebox.fr",
			status: false,
		},

		// ----- ARCHIVES ----- //

		{
			id: "box2archive1",
			box: "Box 2",
			title: "Archives Aaron King",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Aaron_King.jpg",
			status: false,
		},
		{
			id: "box2archive2",
			box: "Box 2",
			title: "Archives Ainmir Oconradh",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Ainmire_Oconradh.jpg",
			status: false,
		},
		{
			id: "box2archive3",
			box: "Box 2",
			title: "Archives Annelijn Dikboom",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Annelijn_dikboom.jpg",
			status: false,
		},
		{
			id: "box2archive4",
			box: "Box 2",
			title: "Archives Annina Kurschner",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Annina_Kurschner.jpg",
			status: false,
		},
		{
			id: "box2archive5",
			box: "Box 2",
			title: "Archives Augustas Alsys",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Augustas_Alsys.jpg",
			status: false,
		},
		{
			id: "box2archive6",
			box: "Box 2",
			title: "Archives Bogdana Nikol",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Bogdana_Nikol.jpg",
			status: false,
		},
		{
			id: "box2archive7",
			box: "Box 2",
			title: "Archives Daisy Vandenbulcke",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Daisy_Vandenbulcke.jpg",
			status: false,
		},
		{
			id: "box2archive8",
			box: "Box 2",
			title: "Archives Dimosthenis Rigas",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Dimosthenis_Rigas.jpg",
			status: false,
		},
		{
			id: "box2archive9",
			box: "Box 2",
			title: "Archives Dominik Jele",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Dominik_Jele.jpg",
			status: false,
		},
		{
			id: "box2archive10",
			box: "Box 2",
			title: "Archives Edvard Kallio",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Edvard_Kallio.jpg",
			status: false,
		},
		{
			id: "box2archive11",
			box: "Box 2",
			title: "Archives Elias Varelas",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Elias_Varelas.jpg",
			status: false,
		},
		{
			id: "box2archive12",
			box: "Box 2",
			title: "Archives Elimena Furino",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Elimena_Furino.jpg",
			status: false,
		},
		{
			id: "box2archive13",
			box: "Box 2",
			title: "Archives Eliza Gaewska",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Eliza_Gaewska.jpg",
			status: false,
		},
		{
			id: "box2archive14",
			box: "Box 2",
			title: "Archives Ere Jakobson",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Ere_Jakobson.jpg",
			status: false,
		},
		{
			id: "box2archive15",
			box: "Box 2",
			title: "Archives Francois Duchamp",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Francois_Duchamp.jpg",
			status: false,
		},
		{
			id: "box2archive16",
			box: "Box 2",
			title: "Archives Horasiu Prunea",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Horasiu_Prunea.jpg",
			status: false,
		},
		{
			id: "box2archive17",
			box: "Box 2",
			title: "Archives Imelda Tuzzolino",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Imelda_Tuzzolino.jpg",
			status: false,
		},
		{
			id: "box2archive18",
			box: "Box 2",
			title: "Archives Ivar Mortensen",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Ivar_Mortensen.jpg",
			status: false,
		},
		{
			id: "box2archive19",
			box: "Box 2",
			title: "Archives James Chambers",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_James_Chambers.jpg",
			status: false,
		},
		{
			id: "box2archive20",
			box: "Box 2",
			title: "Archives Janina Muster",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Janina_Muster.jpg",
			status: false,
		},
		{
			id: "box2archive21",
			box: "Box 2",
			title: "Archives Jorn Frenzel",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Jorn_Frenzel.jpg",
			status: false,
		},
		{
			id: "box2archive22",
			box: "Box 2",
			title: "Archives Karina Galicka",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Karina_Galicka.jpg",
			status: false,
		},
		{
			id: "box2archive23",
			box: "Box 2",
			title: "Archives Konstantin Wallner",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Konstantin_Wallner.jpg",
			status: false,
		},
		{
			id: "box2archive24",
			box: "Box 2",
			title: "Archives Laura Tavernier",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Laura_Tavernier.jpg",
			status: false,
		},
		{
			id: "box2archive25",
			box: "Box 2",
			title: "Archives Lina Syren",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Lina_Syren.jpg",
			status: false,
		},
		{
			id: "box2archive26",
			box: "Box 2",
			title: "Archives Linda Reynolds",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Linda_Reynolds.jpg",
			status: false,
		},
		{
			id: "box2archive27",
			box: "Box 2",
			title: "Archives Marian Bilek",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Marian_Bilek.jpg",
			status: false,
		},
		{
			id: "box2archive28",
			box: "Box 2",
			title: "Archives Marike Vonbraun",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/2_Archives_Marike_Vonbraun.jpg",
			status: false,
		},
		{
			id: "box2archive29",
			box: "Box 2",
			title: "Archives Martin Richard",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Martin_Richard.jpg",
			status: false,
		},
		{
			id: "box2archive30",
			box: "Box 2",
			title: "Archives Mason Reynolds",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Mason_Reynolds.jpg",
			status: false,
		},
		{
			id: "box2archive31",
			box: "Box 2",
			title: "Archives Petar Cojocaru",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Petar_Cojocaru.jpg",
			status: false,
		},
		{
			id: "box2archive32",
			box: "Box 2",
			title: "Archives Riano Della Valle",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Riano_Della_Valle.jpg",
			status: false,
		},
		{
			id: "box2archive33",
			box: "Box 2",
			title: "Archives Samuel Perry",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Samuel_Perry.jpg",
			status: false,
		},
		{
			id: "box2archive34",
			box: "Box 2",
			title: "Archives Taneli Tuominen",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Taneli_Tuominen.jpg",
			status: false,
		},
		{
			id: "box2archive35",
			box: "Box 2",
			title: "Archives Timo Sladie",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/2_Archives_Timo_Sladie.jpg",
			status: false,
		},
	],

	// ---- BOX 3 ---- //

	box3: [
		// ---- DOCUMENT ---- //

		{
			id: "box3document1",
			box: "Box 3",
			title: "Post-it bureau Lauren",
			category: "Document",
			detail: "Un post-it écrit par le tueur et retrouvé dans le bureau de Lauren Fraser",
			poster: "thumbnails/documents/304_Post_it_LD.jpg",
			src: "assets/document/304_Post_it.jpg",
			status: false,
		},
		{
			id: "box3document2",
			box: "Box 3",
			title: "Photo squelette forêt",
			category: "Document",
			detail: "Un squelette déterré dans la forêt des Arbailles",
			poster: "thumbnails/documents/312_Photo_squelette_deterre_LD.jpg",
			src: "assets/document/312_Photo_squelette_deterre.jpg",
			status: false,
		},
		{
			id: "box3document3",
			box: "Box 3",
			title: "Photo hôpital",
			category: "Document",
			detail: "Une photo de personnes inconnues à l'hôpital",
			poster: "thumbnails/documents/313_Photo_Estelle_hopital_LD.jpg",
			src: "assets/document/313_Photo_Estelle_hopital.jpg",
			status: false,
		},
		{
			id: "box3document4",
			box: "Box 3",
			title: "Photo Loïc Valluy",
			category: "Document",
			detail: "Photo de Loïc Valluy trouvée par Tim",
			poster: "thumbnails/documents/314_Photo_Loic_Valluy_LD.jpg",
			src: "assets/document/314_Photo_Loic_Valluy.jpg",
			status: false,
		},
		{
			id: "box3document5",
			box: "Box 3",
			title: "Dossier médical Céline",
			category: "Document",
			detail: "Dossier médical de Céline Valluy retrouvé chez elle",
			poster: "thumbnails/documents/316_Dossier_Celine_LD.jpg",
			src: "assets/document/316_Dossier_Celine.pdf",
			status: false,
		},
		{
			id: "box3document6",
			box: "Box 3",
			title: "Dossier médical Estelle",
			category: "Document",
			detail: "Dossier médical d'Estelle Barloigus récupéré sur le site d'ASCLEA",
			poster: "thumbnails/documents/317_Dossier_Estelle_LD.jpg",
			src: "assets/document/317_Dossier_Estelle.pdf",
			status: false,
		},
		{
			id: "box3document7",
			box: "Box 3",
			title: "Livre complet 'Lilith et la guérison des maux'",
			category: "Document",
			detail: "Version complète du livre 'Lilith et la guérison des maux' retrouvé chez Céline",
			poster: "thumbnails/documents/319_Livre_Lilith_complet_screenshot.jpg",
			src: "assets/document/319_Livre_Lilith_complet.pdf",
			status: false,
		},
		{
			id: "box3document8",
			box: "Box 3",
			title: "Reçu de la poste",
			category: "Document",
			detail: "La box a été envoyée par Céline, on dirait",
			poster: "thumbnails/documents/320_Recu_poste_LD.jpg",
			src: "assets/document/320_Recu_poste.pdf",
			status: false,
		},
		{
			id: "box3document9",
			box: "Box 3",
			title: "Carnet d'Estelle",
			category: "Document",
			detail: "Carnet d'Estelle Barloigus retrouvé dans la cave de Céline Valluy",
			poster: "thumbnails/documents/321_Carnet_Estelle_LD.jpg",
			src: "assets/document/321_Carnet_Estelle.pdf",
			status: false,
		},
		{
			id: "box3document10",
			box: "Box 3",
			title: "Tableau des victimes",
			category: "Document",
			detail: "Sordide tableau de chasse du Tueur au Tarot avec le détail des victimes",
			poster: "thumbnails/documents/322_Tableau_Celine_LD.jpg",
			src: "assets/document/322_Tableau_Celine.jpg",
			status: false,
		},
		{
			id: "box3document11",
			box: "Box 3",
			title: "Arbre généalogique",
			category: "Document",
			detail: "L'arbre généalogique de la famille Valluy-Barloigus trouvé chez Céline Valluy",
			poster: "thumbnails/documents/325_Arbre_genealogique_LD.jpg",
			src: "assets/document/325_Arbre_genealogique.pdf",
			status: false,
		},
		{
			id: "box3document12",
			box: "Box 3",
			title: "Liste des donneurs potentiels",
			category: "Document",
			detail: "Une étrange pile de dossiers médicaux retrouvée dans la cave de Céline Valluy",
			poster: "thumbnails/documents/327_Liste_des_donneurs_LD.jpg",
			src: "assets/document/327_Liste_des_donneurs.jpg",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //

		{
			id: "box3audio1",
			box: "Box 3",
			title: "Débrief Lauren",
			category: "Audio",
			detail: "Lauren nous raconte son enlèvement",
			poster: "assets/photos-personnages/lauren.jpg",
			img1: "assets/photos-personnages/lauren.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/303-debrief-lauren.mp3",
			srcTranscript: "assets/transcripts/303_Debrief_Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio2",
			box: "Box 3",
			title: "Interrogatoire Leonie Brugmann",
			category: "Audio",
			detail: "Amie de Bebekka Auer",
			poster: "assets/photos-personnages/Leonie-Brugmann.jpg",
			img1: "assets/photos-personnages/Leonie-Brugmann.jpg",
			img2: "assets/photos-personnages/Rebekka-Auer.jpg",
			srcAudio: "sounds/311-interrogatoire-leonie-brugmann-rebekka-auer.mp3",
			srcTranscript: "assets/transcripts/311_Interrogatoire_Leonie_Brugmann-Rebekka_Auer_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio3",
			box: "Box 3",
			title: "Interrogatoire Yann Lacroix",
			category: "Audio",
			detail: "Médecin en charge de la greffe d'Estelle Barloigus",
			poster: "assets/photos-personnages/Yann Lacroix.jpg",
			img1: "assets/photos-personnages/Yann Lacroix.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/312-interrogatoire-yann-lacroix-raphaelle.mp3",
			srcTranscript: "assets/transcripts/312_Interrogatoire_Yann_Lacroix-Raphaelle_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio4",
			box: "Box 3",
			title: "Interrogatoire François Duchamp",
			category: "Audio",
			detail: "Profiler mentor de Lauren Fraser",
			poster: "assets/photos-personnages/Francois-Duchamp.jpg",
			img1: "assets/photos-personnages/Francois-Duchamp.jpg",
			img2: "assets/photos-personnages/raphaelle.jpg",
			srcAudio: "sounds/313-interrogatoire-francois-duchamp-raphaelle.mp3",
			srcTranscript: "assets/transcripts/313_Interrogatoire_Francois_Duchamp-Raphaelle_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box3video1",
			box: "Box 3",
			title: "Briefing box 3",
			category: "Video",
			detail: "Il y a urgence, il faut retrouver Lauren et coincer le tueur !",
			poster: "thumbnails/video/DB_S02_301_def_miniature.jpg",
			src: "videos/db-s02-301-def.mp4",
			status: false,
		},
		{
			id: "box3video2",
			box: "Box 3",
			title: "Cave de Céline",
			category: "Video",
			detail: "On a retrouvé Lauren saine et sauve",
			poster: "thumbnails/video/DB_S02_302_def_miniature.jpg",
			src: "videos/db-s02-302-def.mp4",
			status: false,
		},
		{
			id: "box3video3",
			box: "Box 3",
			title: "Interrogatoire de Céline Valluy",
			category: "Video",
			detail: "L'affaire du Tueur au Tarot est enfin classée",
			poster: "thumbnails/video/db-s02-309-def-miniature.jpg",
			src: "videos/db-s02-309-def.mp4",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box3lieu1",
			box: "Box 3",
			title: "Forêt",
			category: "Lieu",
			detail: "Une escapade dans la forêt des Arbailles ",
			poster: "thumbnails/lieux/301_Foret_low.jpg",
			src: "https://fouille.foret.detectivebox.fr",
			status: false,
		},
		{
			id: "box3lieu2",
			box: "Box 3",
			title: "Chez Céline",
			category: "Lieu",
			detail: "Fouille de l'appartement de Céline Valluy",
			poster: "thumbnails/lieux/302_chez_Celine_low.jpg",
			src: "https://fouille.celine.detectivebox.fr",
			status: false,
		},
		{
			id: "box3lieu3",
			box: "Box 3",
			title: "Cave",
			category: "Lieu",
			detail: "Que cache Céline dans sa cave ?",
			poster: "thumbnails/lieux/303_Planque_3_cave_low.jpg",
			src: "https://fouille.cave.detectivebox.fr",
			status: false,
		},

		// ----- ARCHIVES ----- //

		{
			id: "box3archive1",
			box: "Box 3",
			title: "Archives Agnes Vouchiar",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/3_Archives_Agnes_Vouchiar.jpg",
			status: false,
		},
		{
			id: "box3archive2",
			box: "Box 3",
			title: "Archives Giuseppe Rossi",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/3_Archives_Giuseppe_Rossi.jpg",
			status: false,
		},
		{
			id: "box3archive3",
			box: "Box 3",
			title: "Archives Leonie Brugmann",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/3_Archives_Leonie_Brugmann.jpg",
			status: false,
		},
		{
			id: "box3archive4",
			box: "Box 3",
			title: "Archives Maria Gruber",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_femme_low.jpg",
			src: "assets/archive/3_Archives_Maria_Gruber.jpg",
			status: false,
		},
		{
			id: "box3archive5",
			box: "Box 3",
			title: "Archives Yann Lacroix",
			category: "Archive",
			detail: "",
			poster: "assets/archive/Archives_miniatures_homme_low.jpg",
			src: "assets/archive/3_Archives_Yann_Lacroix.jpg",
			status: false,
		},
	],
};
