export const dataAdele = {
	box2: [
		{
			ask: ["autopsiegarraud", "autopsiecharlesgarraud", "vomi", "vomigarraud", "vomicharlesgarraud", "vomiprison"],
			text: [
				"Alors j'ai mis ça à analyser.",
				"Il semblerait que Garraud ait essayé d'avaler quelque chose avant de mourir. Et j'avais raison !",
				"Raphaëlle m'a permis d'avoir une autopsie plus complète.",
				"C'était bien planqué mais devinez ce que j'ai trouvé dans son corps ? Ce magnifique papier !",
				"C'était un peu glauque par contre…",
				"Enfin bref, c'est fou ce qu'on peut retrouver dans un corps, non ?”",
			],
			srcComment: "sounds/202-commentaires-adele-1.mp3",
			id: "box2document4",
			title: "Papier avalé par Garraud",
			src: "assets/document/215_Papier_avale.jpg",
			status: false,
		},
		{
			ask: ["b759030", "echantillonb759030", "analysesang", "echantillonsang"],
			text: [
				"J'ai analysé l'échantillon avant de vous envoyer le dossier.",
				"L'échantillon B75-9030 ne correspond à l'ADN d'aucune victime rapportée au tueur et certainement pas à Xavier.",
				"C'est une personne de groupe B et non répertorié dans la base criminelle européenne.",
				"C'est donc quelqu'un qui ne s'est jamais fait attraper par la police, même pour un délit.",
				"J'ai poussé l'analyse un peu plus loin, j'y ai diagnostiqué une créatininémie.",
				"En gros, ça veut dire que le propriétaire de cette goutte de sang avait un problème rénal.",
			],
			srcComment: "sounds/202-commentaires-adele-2.mp3",
			status: false,
		},
		{
			ask: ["organes", "organesfrigo", "organesdufrigo", "membresfrigo", "organesretrouvesdanslefrigo"],
			text: [
				"Alors, ce que je peux vous dire, c'est que ça a été bien conservé, probablement dans du formol.",
				"Il y en avait donc peut-être qui avait plusieurs années.",
				"Pour la petite liste, on a donc :",
				"un cou, un estomac, une rotule, des organes génitaux masculins, une tête, un rein, un poumon, un coeur et un morceau de jambe.",
				"On pourrait presque se croire dans Frankenstein non ?",
			],
			srcComment: "sounds/202-commentaires-adele-3.mp3",
			status: false,
		},
	],
	box3: [
		{
			ask: [
				"squelette",
				"foret",
				"analysecorps",
				"corpsdeterre",
				"corpsdetere",
				"squellette",
				"corpsdelaforet",
				"corpsforet",
				"squeletteforet",
				"corpsforetarbailles",
				"squelettearbailles",
				"squeletteforetarbailles",
				"squelettedelaforet",
				"squelettedesarbailles",
			],
			text: [
				"Je lance l'analyse du corps pour comparaison avec le fichier des disparus, mais ça risque de prendre un peu de temps...",
				"Sinon, je peux déjà vous dire qu'il est mort assassiné, par un coup de couteau.",
				"Ah, et c'est un homme, enfin c'était...",
			],
			srcComment: "sounds/301-commentaire-adele-sur-corps-1.mp3",
			status: false,
		},
		{
			ask: ["loicvalluy"],
			text: [
				"Loïc Valluy... J'ai rentré ça dans mon fichier et vous savez quoi ?",
				"Vous avez deviné ? Non ?",
				"C'est le squelette que vous avez trouvé dans la forêt !",
			],
			srcComment: "sounds/301-commentaire-adele-sur-corps-2.mp3",
			status: false,
		},
		{
			ask: ["echantillonterre", "echantillonech78b", "ech78b", "echantillondeterre", "echantillonterreech78b"],
			text: [
				"Ah, l'échantillon de terre qu'on a trouvé.",
				"J'ai fait la pré-analyse mais je n'ai pas eu le temps de faire plus…",
				"et puis, les fleurs, je vous avoue que c'est pas trop mon truc.",
				"Vous pouvez essayer de déterminer ce que c'est ?",
				"Si on trouve la provenance, on saura peut-être où est Lauren ? ",
				"Je vous ai mis l'herbier pour vous aider.",
			],
			srcComment: "sounds/301-commentaire-adele-sur-corps-3.mp3",
			status: false,
		},
	],
};
